config/routes.rb
JobSearch::Application.routes.draw do
  
  resources :jobs

  root 'home#index'

  get 'add' => 'static_pages#add'

end

app/models/job.rb
class Job
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  protect_from_forgery with: :exception

  def manipulate_xml(data)
  	x = data["rss"]
  	y = x["channel"]
  	if y["totalResults"] == "0"
  		return []
  	else
  		all_items = y["item"]
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  require 'rss'
  require 'open-uri'
  require 'actionpack/action_caching'
  respond_to :html, :json
  caches_action :index, :cache_path => Proc.new { |c| c.request.url }, :expires_in => 10.minute


  def index
    if params[:remote] == 1
      @remote = 'true'
    else
      @remote = 'false'
    end
    @keywords = params[:keywords].tr(" ", "+").gsub("#", "%23")
    @location = params[:location].tr(" ", "")
    
    #reddit_jobs
    if @keywords.present?
      reddit_response = HTTParty.get("http://www.reddit.com/r/forhire/search.json?q=#{@keywords}+#{@location}&sort=new&restrict_sr=on&t=month")
      reddit_jobs_pre = JSON.parse(reddit_response.body)["data"]["children"]
      @reddit_jobs = reddit_jobs_pre.select { |job| job["data"]["link_flair_text"] == "Hiring" }
    end
    
    #craigslist_jobs
    if @location.present? && @keywords.present?
      begin
        craigslist_url = "http://#{@location}.craigslist.org/search/jjj?catAbb=jjj&query=#{@keywords}&s=0&format=rss"
        open(craigslist_url) do |rss|
          @craigslist_jobs = RSS::Parser.parse(rss).items
        end
      rescue SocketError
        @craigslist_jobs = []
      rescue OpenURI::HTTPError
        @craigslist_jobs = []
      rescue RSS::NotWellFormedError
        @craigslist_jobs = []
      end
    end

    #ruby_now_jobs
    if %w(ruby rails).any? {|str| params[:keywords].downcase.include? str} || params[:keywords].empty?
      ruby_now_response = HTTParty.get("http://feeds.feedburner.com/jobsrubynow?format=xml")
      if @location.empty?
        @ruby_now_jobs = manipulate_xml(ruby_now_response)
      else
        @ruby_now_jobs = []
        @now_jobs = manipulate_xml(ruby_now_response)
        @now_jobs.map do |job|
          if job['title'].downcase.include? params[:location].downcase
            @ruby_now_jobs << job
          end
        end
      end
    else
      @ruby_now_jobs = []
    end

    #stackoverflow_jobs
    stackoverflow_response = HTTParty.get("http://careers.stackoverflow.com/jobs/feed?searchTerm=#{@keywords}&location=#{@location}")
    pre_stackoverflow = manipulate_xml(Hash.from_xml(stackoverflow_response))

    if @location.present? && params[:remote] == "1"
      stackoverflow_response_remote = HTTParty.get("http://careers.stackoverflow.com/jobs/feed?searchTerm=#{@keywords}&allowsremote=true")
      pre_stackoverflow_remote = manipulate_xml(Hash.from_xml(stackoverflow_response_remote))
      pre_stackoverflow_remote.each do |job|
        pre_stackoverflow << job
        pre_stackoverflow.uniq! { |job| job["link"] }
      end
    end
    if pre_stackoverflow.is_a? Array
      @stackoverflow_jobs = pre_stackoverflow.sort_by { |job| job["updated"] }.reverse
    else
      @stackoverflow_jobs = []
      @stackoverflow_jobs << pre_stackoverflow
    end

    #authentic_jobs
    authentic_response = HTTParty.get("http://www.authenticjobs.com/api/?api_key=#{ENV["AUTHENTIC_JOBS_API_KEY"]}&method=aj.jobs.search&keywords=#{@keywords}&location=#{@location}&perpage=20&begin_date=#{1.month.ago.to_i}&format=json")
    @authentic_jobs = JSON.parse(authentic_response.body)

    #github_jobs
    github_response = HTTParty.get("http://jobs.github.com/positions.json?description=#{@keywords}&location=#{@location}")    
    @github_jobs = JSON.parse(github_response.body)

    if @location.present? && params[:remote] == "1"
      github_remote_response = HTTParty.get("http://jobs.github.com/positions.json?description=#{@keywords}&location=remote")
      github_remote_jobs = JSON.parse(github_remote_response.body)
      github_remote_jobs.each do |job|
        @github_jobs << job
      end      
      @github_jobs.uniq! { |job| job["url"] }
      @github_jobs.each do |job|
        job[:time] = Time.parse(job["created_at"])
      end
      @github_jobs = @github_jobs.sort_by { |job| job[:time] }.reverse
    end

    #we_work_remotely_jobs
    if params[:remote] == "1"
      we_work_remote_response = HTTParty.get("https://weworkremotely.com/categories/2/jobs.rss")
      @we_work_remote_jobs = manipulate_xml(Hash.from_xml(we_work_remote_response))
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/jobs/_authentic_jobs.html.erb
<% unless @authentic_jobs["listings"]["total"] == 0 %>
  <div class="span4 well pre-scrollable">
    <center><%= image_tag "authentic_jobs.png" %></center>
    <br>
    <% @authentic_jobs["listings"]["listing"].each do |job| %>
      <% if job["company"].present? && job["company"]["location"].present? %>
        <% company = " at " + job["company"]["name"] + " (#{job["company"]["location"]["city"]})" %>
      <% else %>
        <% company = "" %>
      <% end %>
      <% if job["telecommuting"] == 1 %>
        <% company << " (Remote)" %>
      <% end %>
      <%= link_to job["title"] + company, job["url"] %>
      <br>
      <%= job["post_date"][0..-9] %>
      <br><br>
    <% end %>
  </div>
<% end %>

app/views/jobs/_craigslist_jobs.html.erb
<% if @craigslist_jobs.present? %>
  <div class="span4 well pre-scrollable">
    <center><%= image_tag "craigslist_jobs.gif" %></center>
    <br>
    <% @craigslist_jobs.each do |job| %>
      <%= link_to job.dc_title, job.dc_source %>
      <br>
      <%= job.dc_date.strftime("%d %b, %Y") %>
      <br><br>
    <% end %>
  </div>
<% end %>

app/views/jobs/_github_jobs.html.erb
<% if @github_jobs.present? %>
  <div class="span4 well pre-scrollable">
    <center><%= image_tag "github_jobs.png" %></center>
    <% @github_jobs.each do |job| %>
      <%= link_to "#{job['title']} at #{job['company']} (#{job['location']})", job["url"]  %>
      <br>
      <%= job["created_at"][0..-19] %>
      <br><br>
    <% end %>
  </div>
<% end %>

app/views/jobs/_reddit_jobs.html.erb
<% if @reddit_jobs.present? %>
  <div class="span4 well pre-scrollable">
    <center><%= image_tag "reddit_jobs.svg" %></center>
    <br>
    <% @reddit_jobs.each do |job| %>
      <%= link_to job["data"]["title"], job["data"]["url"]  %>
      <br>
      <%= Time.at(job["data"]["created_utc"]).strftime("%d %b, %Y") %>
      <br><br>
    <% end %>
  </div>
<% end %>

app/views/jobs/_ruby_now_jobs.html.erb
<% if @ruby_now_jobs.present? %>
  <div class="span4 well pre-scrollable">
    <center><%= image_tag "ruby_now.png" %></center>
    <br>   
    <% @ruby_now_jobs.each do |job| %>
      <% job["title"].gsub!("at:", "-") %>
      <%= link_to job["title"], job["origLink"]  %>
      <br>
      <%= job["pubDate"][0..-13] %>
      <br><br>
    <% end %>
  </div>
<% end %>

app/views/jobs/_stackoverflow_jobs.html.erb
<% if @stackoverflow_jobs.present? %>
  <div class="span4 well pre-scrollable">
    <center><%= image_tag "stackoverflow_careers.jpg" %></center>
      <br>
      <% @stackoverflow_jobs.each do |job| %>
          <%= link_to job["title"] , job["link"]  %>
          <br>
          <%= job["pubDate"][0..-11] %>
          <br><br>
    <% end %>
  </div>
<% end %>

app/views/jobs/_we_work_remote_jobs.html.erb
<% if @we_work_remote_jobs.present? %>
  <div class="span4 well pre-scrollable">
    <center><%= image_tag "weworkremote.jpg" %></center>
    <br>   
    <% @we_work_remote_jobs.each do |job| %>
      <%= link_to job["title"], job["link"]  %>
      <br>
      <%= job["pubDate"][0..-15] %>
      <br><br>
    <% end %>
  </div>
<% end %>

app/views/jobs/index.html.erb
<br>
<div class="container-fluid">
  <div class="row-fluid", id="wells">
    <%= render "github_jobs" %>
    <%= render "stackoverflow_jobs" %>
    <%= render "ruby_now_jobs" %>
    <%= render "authentic_jobs" %>
    <%= render "reddit_jobs" %>
    <%= render "craigslist_jobs" %>
    <%= render "we_work_remote_jobs" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "JobSearch" %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">        
          <%= link_to 'Add a Job Board', add_path, html_options = {class: "brand", style: "float: right"} %>
          <div class="form-inline">      
            <%= form_tag(jobs_path, method: 'get', style: "float: left") do %>
              <%= label_tag(:keywords, "Keyword(s)") %>
              <%= text_field_tag(:keywords) %> &nbsp
              <%= label_tag(:location, "City") %>
              <%= text_field_tag(:location) %>
              <%= submit_tag("Search", class: "btn") %> &nbsp
              <%= check_box_tag(:remote) %>
              <%= label_tag(:remote, "Include Remote Jobs") %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid">
      <div class="row-fluid">
        <div>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/static_pages/add.html.erb
<a href="https://github.com/jonfriese/job_search">Here's the source code! Have at it!</a>